# Generated by Django 4.2.2 on 2023-06-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='name'),
        ),
    ]
